### ISSUE TITLE
Lesson 8. Matrix

### ISSUE THREAD

**Issue by milkina** [yashchenko-oleksandr/java_YashchenkoAlexander#2]
1. В конструкт. Matrix(int numberLines, int numberColumns, double[][] array)
строка   this.array = new double[numberLines][numberColumns];
не нужна.
2. Попробуйте умножить матрицы 3x2 и 2х3 - выброситься exception.
3. sumMatrixs, multiplicationNumberOnMatrixs,print - на вход передавайте объект матрицы.
4. Лучше не вызывать метод print из методов sumMatrixs, multiplicationNumberOnMatrixs, multiplicationMatrixsOnMatrixs. Вызовите его из main.  Пусть ваши методы выполняют только одну операцию.
5. Лучше назвать методы multiplicationNumberOnMatrixs, multiplicationMatrixsOnMatrixs просто multiplication.

**Comment by milkina** [comment]
Done, но:
1. убрать ненужные пустые строки
2. sumMatrixs - лучше просто sum. И так понятно, что складываются матрицы.

**Comment by yashchenko-oleksandr** [comment]
Исправлено
