### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by milkina** [yashchenko-oleksandr/java_YashchenkoAlexander#5]
Может сделать отдельный if для условия  if (A == B) ?

**Comment by yashchenko-oleksandr** [comment]
в виде метода ?

**Comment by milkina** [comment]
Нет, в том же методе:
if(A>B){...}
else if(A<B){...}
else{...}

**Comment by yashchenko-oleksandr** [comment]
Справедливое замечание. Сделаю!

**Comment by yashchenko-oleksandr** [comment]
Переделал.

**Comment by milkina** [comment]
Done, но еще  -зачем метод возвращает значение типа int? Сделайте void.

**Comment by yashchenko-oleksandr** [comment]
Исправлено
