### ISSUE TITLE
Цветы

### ISSUE THREAD

**Issue by milkina** [yashchenko-oleksandr/java_YashchenkoAlexander#6]
1.   static int count; - добавьте модификатор
2.  public double valueCarnations;  - почему public?
3. Желательно переопределять в создаваемом классе методы  equals .
4.  MainFlower - неотформатировано
5. MainFlower  -вынести дублирующийся код в отд. метод

**Comment by yashchenko-oleksandr** [comment]
Исправил, проверьте пожалуйста.

**Comment by milkina** [comment]
1. int allCount в методе print не используется. Его можно убрать.

**Comment by yashchenko-oleksandr** [comment]
Почему не используется ? Используется !
